CREATE TABLE users (
  id SERIAL PRIMARY KEY ,
  username  VARCHAR(50) UHIQUE NOT NULL,
  password VARCFHAR(50) NOT NULL,
  role VARCHAR(50) NOT NULL);


CREATE TABLE customers(
  id SERIAL PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL,
  CONTACT_DETAILS VARCHAR(100),
  ORDER_HISTORY JSONB);

CREATE TABLE orders(
  id SERIAL PRIMARY KEY,
  customer_id INTEGER REFERCES customer(id),
  order_details JSONB,
  order_status VARCHAR(50) NOT NULL,
  timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
